import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

test('zengin portföy ekranı günlük değerlendirmeyi ve tam müşteri kartını korur', async () => {
  const wrapper = await readFile(new URL('../src/portfolio_company_link_entry.js', import.meta.url), 'utf8');
  const recovery = await readFile(new URL('../src/portfolio_api_recovery_entry.js', import.meta.url), 'utf8');
  const embedded = await readFile(new URL('../src/portfolio_clean_page.js', import.meta.url), 'utf8');
  const page = await readFile(new URL('../public/musteri-portfoyu-v2.html', import.meta.url), 'utf8');
  const index = await readFile(new URL('../public/index.html', import.meta.url), 'utf8');
  const worker = await readFile(new URL('../src/index.js', import.meta.url), 'utf8');

  assert.match(wrapper, /CLEAN_PORTFOLIO_HTML/);
  assert.match(wrapper, /clean-v3-inline/);
  assert.doesNotMatch(wrapper, /env\.ASSETS\.fetch/);
  assert.match(recovery, /restorePortfolioCustomers/);
  assert.match(wrapper, /\/api\/portfolio-bootstrap/);
  assert.match(wrapper, /directBootstrap/);
  assert.match(wrapper, /directMeetings/);
  assert.match(wrapper, /\/api\/portfolio-meetings/);
  assert.match(wrapper, /restorePortfolioCustomers/);
  assert.match(wrapper, /x-crm-portfolio-api/);

  for (const source of [embedded,page]) {
    assert.match(source, /PORTFOY RICH V19/);
    assert.match(source, /Günlük Değerlendirme/);
    assert.match(source, /<th>Son Görüşme<\/th>/);
    assert.match(source, /Görüşmeler & Notlar/);
    assert.match(source, /Teklifler/);
    assert.match(source, /Müşteri Analizi/);
    assert.doesNotMatch(source, /data-tab="orders"/);
    assert.doesNotMatch(source, /id="tabOrders"/);
    assert.doesNotMatch(source, /orderSummary/);
    assert.match(source, /Gelen/);
    assert.match(source, /Giden/);
    assert.match(source, /grid-template-columns:repeat\(5,minmax\(120px,1fr\)\)/);
    assert.match(source, /Memnuniyet Durumu/);
    assert.match(source, /Şikayet Durumu/);
    assert.match(source, /Şikayet \/ Çözüm Notu/);
    assert.match(source, /Kaybedilme Sebebi/);
    assert.match(source, /Müşteri Analizini Kaydet/);
    assert.match(source, /Müşteri analizi kaydedildi/);
    assert.match(source, /ANALYSIS_MARKER/);
    assert.match(source, /function saveCustomerAnalysis\(\)/);
    assert.match(source, /company-open-btn/);
    assert.match(source, /body:not\(\.customer-open\) \.workspace/);
    assert.match(source, /body\.customer-open \.workspace/);
    assert.match(source, /minmax\(690px,1\.08fr\)/);
    assert.match(source, /detail-title\{font-size:20px/);
    assert.match(source, /info-row input,\.info-row select\{font-size:12\.5px/);
    assert.match(source, /tab\{font-size:12px/);
    assert.match(source, /body:not\(\.customer-open\) \.workspace \.detail\{display:none/);
    assert.match(source, /function normalizeRows\(data,key\)/);
    assert.match(source, /api\('\/api\/portfolio-bootstrap\?ts='\+Date\.now\(\)\)/);
    assert.match(source, /PORTFOLIO_CACHE_KEY/);
    assert.match(source, /function loadMeetingData\(\)/);
    assert.match(source, /api\('\/api\/portfolio-meetings\?ts='\+Date\.now\(\)\)/);
    assert.doesNotMatch(source, /Promise\.allSettled\(\[api\('\/api\/customers/);
    assert.match(source, /function closeCustomerDetail\(\)/);
    assert.match(source, /document\.body\.classList\.add\('customer-open'\)/);
    assert.doesNotMatch(source, /portfolio-fullscreen-detail\.js/);
    assert.doesNotMatch(source, /portfolio-fullscreen-stable\.js/);
    assert.match(source, /Yetkili Kişiler/);
    assert.match(source, /Yeni Görüşme \/ Not Ekle/);
    assert.match(source, /function saveMeetingNote\(\)/);
    assert.match(source, /note-date/);
    assert.match(source, /date:today\(\)/);
    assert.match(source, /follow-future/);
    assert.match(source, /follow-overdue/);
    assert.match(source, /follow-today/);
    assert.match(source, /function isFuture\(c\)/);
    assert.match(source, /@keyframes dueTodayPulse/);
    assert.match(source, /Gelecek/);
    assert.match(source, /Geçmiş/);
    assert.match(source, /function addContactPerson\(\)/);
    assert.match(source, /openContactIndex/);
    assert.match(source, /portfolioLoadInFlight/);
    assert.match(source, /meetingLoadInFlight/);
    assert.match(source, /async function ensureSelectedHistory\(\)/);
    assert.match(source, /function refreshPortfolioDataSilently\(\)/);
    assert.match(source, /const cached=readCustomerCache\(\)/);
    assert.doesNotMatch(source, /await loadAll\(selected\.id\)/);
  }

  assert.match(page, /data-tab="mails"/);
  assert.match(page, /id="tabMails"/);
  assert.match(page, /id="mailHistory"/);
  assert.doesNotMatch(page, /<th>Mail<\/th>/);
  assert.match(page, /id="meetingNoteDate"/);
  assert.match(page, /id="meetingNoteText"/);
  assert.match(page, /grid-template-columns:repeat\(5,minmax\(120px,1fr\)\)/);
  assert.match(page, /embedded/);
  assert.match(page, /location\.replace\('\/\?page=portfolio'\)/);
  assert.match(page, /window\.parent\.activateCrmPage\('customers'\)/);

  assert.match(index, /data-page="portfolio"/);
  assert.match(index, /id="portfolioFrame"/);
  assert.match(index, /musteri-portfoyu\.html\?embedded=1/);
  assert.match(index, /CRM_PAGE_CACHE_MS=900000/);
  assert.match(index, /requestAnimationFrame\(\(\)=>requestAnimationFrame/);
  assert.match(index, /prewarmPortfolioFrame/);
  assert.doesNotMatch(index, /requestIdleCallback\(prewarmPortfolioFrame/);
  assert.match(index, /crmSwitching/);

  assert.doesNotMatch(embedded, /id=\\\"dResultSelect\\\"/);
  assert.doesNotMatch(embedded, /id=\\\"newNote\\\"/);
  assert.match(embedded, /id=\\\"dContactPicker\\\"/);
  assert.match(embedded, /function makePrimaryContact\(i\)/);
  assert.match(embedded, /primary-contact-badge/);
  assert.match(embedded, /id=\\\"mailComposeSend\\\"/);
  assert.match(embedded, /function openMailComposer\(\)/);
  assert.match(embedded, /function sendCustomerMail\(\)/);
  assert.match(embedded, /\/api\/customer-mail\/send/);
  assert.match(embedded, /function applyMeetingResultLocally\(result\)/);
  assert.match(embedded, /Sonuç müşteri kartına işlendi/);
  assert.match(worker, /b\.result==='Beklemede'\|\|b\.result==='Tekrar Görüşülecek'/);
  assert.match(worker, /b\.result==='Sonuçlanmamış'/);

  const start = page.lastIndexOf('<script>');
  const end = page.indexOf('</script>', start);
  assert.ok(start >= 0 && end > start, 'portföy sayfasında inline script bulunmalı');
  const inlineScript = page.slice(start + '<script>'.length, end);
  assert.doesNotThrow(() => new Function(inlineScript));
});
