package com.musteritakipcrm.alarm;
import org.json.*;import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;
final class Api{
 static final String BASE="https://musteri-takip-crm.musteritakipcrm.workers.dev";
 static final class Reminder{final int id;final String remindAt;final long when;final String title;final String body;Reminder(int i,String r,long w,String t,String b){id=i;remindAt=r;when=w;title=t;body=b;}String key(){return id+"|"+remindAt;}}
 static final class Entry{final int id;final String date,note,remindAt,status;Entry(int i,String d,String n,String r,String s){id=i;date=d;note=n;remindAt=r;status=s;}boolean archived(){return "Yapıldı".equals(status);}}
 static String pair(String code,String label)throws Exception{return request("POST","/api/native-alarm/pair","",new JSONObject().put("code",code).put("label",label)).getString("token");}
 static List<Entry> agenda(String token)throws Exception{JSONArray a=request("GET","/api/native-alarm/agenda",token,null).optJSONArray("entries");List<Entry> x=new ArrayList<>();if(a!=null)for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);x.add(new Entry(o.getInt("id"),o.optString("entry_date",""),o.optString("note",""),o.optString("remind_at",""),o.optString("entry_status","Yapılacak")));}return x;}
 static void addEntry(String token,String date,String note,String remind)throws Exception{request("POST","/api/native-alarm/agenda",token,new JSONObject().put("entry_date",date).put("note",note).put("remind_at",remind));}
 static void archive(String token,int id,boolean archived)throws Exception{request("POST","/api/native-alarm/agenda/"+id,token,new JSONObject().put("archived",archived));}
 static void deleteEntry(String token,int id)throws Exception{request("DELETE","/api/native-alarm/agenda/"+id,token,null);}
 static List<Reminder> reminders(String token)throws Exception{JSONObject out=request("GET","/api/native-alarm/reminders",token,null);JSONArray list=out.optJSONArray("reminders");List<Reminder> result=new ArrayList<>();if(list==null)return result;for(int i=0;i<list.length();i++){JSONObject r=list.getJSONObject(i);result.add(new Reminder(r.getInt("id"),r.getString("remind_at"),r.getLong("when"),r.optString("title","Ajanda Alarm"),r.optString("body","Hatırlatma zamanı geldi.")));}return result;}
 static void ack(String token,int id,String remindAt)throws Exception{request("POST","/api/native-alarm/ack",token,new JSONObject().put("id",id).put("remind_at",remindAt));}
 static JSONObject ping(String token)throws Exception{return request("GET","/api/native-alarm/ping",token,null);}
 private static JSONObject request(String method,String path,String token,JSONObject body)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL(BASE+path).openConnection();c.setConnectTimeout(12000);c.setReadTimeout(12000);c.setRequestMethod(method);c.setRequestProperty("Accept","application/json");if(token!=null&&!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json; charset=utf-8");try(OutputStream os=c.getOutputStream()){os.write(body.toString().getBytes(StandardCharsets.UTF_8));}}int status=c.getResponseCode();InputStream in=status>=200&&status<300?c.getInputStream():c.getErrorStream();String text=read(in);JSONObject out=text.isEmpty()?new JSONObject():new JSONObject(text);if(status<200||status>=300)throw new IOException(out.optString("error","Sunucu hatası: "+status));return out;}
 private static String read(InputStream in)throws IOException{if(in==null)return "";try(BufferedReader r=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){StringBuilder b=new StringBuilder();String line;while((line=r.readLine())!=null)b.append(line);return b.toString();}}
}
