package com.musteritakipcrm.alarm;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.security.MessageDigest;import java.text.SimpleDateFormat;import java.util.*;

public class MainActivity extends Activity{
 private static final String PREF="crm_alarm", M2="\u2063\u200B", M3="\u2063\u200C";
 private LinearLayout body,list; private int page=1; private boolean archive=false,n3Unlocked=false; private String calendarDay=""; private List<Api.Entry> cache=new ArrayList<>();
 @Override public void onCreate(Bundle b){super.onCreate(b);AlarmRingingService.ensureChannels(this);requestPermissionsIfNeeded();setContentView(ui());if(token().isEmpty())pairDialog();else{startServiceNow();load();}}
 private LinearLayout ui(){LinearLayout root=v();root.setBackgroundColor(Color.rgb(247,249,251));TextView h=t("📝 AJANDAM",21,true);h.setGravity(Gravity.CENTER);h.setPadding(18,15,18,15);h.setBackgroundColor(Color.rgb(255,202,40));root.addView(h,new LinearLayout.LayoutParams(-1,-2));body=v();body.setPadding(10,7,10,10);root.addView(body,new LinearLayout.LayoutParams(-1,-1));buildPage();return root;}
 private void buildPage(){body.removeAllViews();LinearLayout nav=new LinearLayout(this);String[] names={"NOT 1","NOT 2","🔒 NOT 3","📅 TAKVİM"};for(int i=0;i<4;i++){final int p=i+1;Button b=new Button(this);b.setText(names[i]);b.setTextSize(11);b.setMinHeight(42);b.setOnClickListener(x->openPage(p));nav.addView(b,new LinearLayout.LayoutParams(0,-2,1));}body.addView(nav);LinearLayout tools=new LinearLayout(this);Button add=new Button(this);add.setText("+ YENİ");add.setTextSize(12);add.setOnClickListener(x->{if(connected())editForm(null,false,page==4?1:page,calendarDay);});Button arc=new Button(this);arc.setText(archive?"✓ ARŞİV":"ARŞİV");arc.setTextSize(12);arc.setOnClickListener(x->{archive=!archive;buildPage();if(page==4)renderCalendar();else render(cache);});tools.addView(add,new LinearLayout.LayoutParams(0,-2,1));tools.addView(arc,new LinearLayout.LayoutParams(0,-2,1));body.addView(tools);if(page==4){renderCalendar();return;}ScrollView sc=new ScrollView(this);list=v();sc.addView(list);body.addView(sc,new LinearLayout.LayoutParams(-1,0,1));if(token().isEmpty())pairDialog();else render(cache);}
 private void openPage(int p){if(p==3&&!n3Unlocked){pinDialog();return;}if(page==3&&p!=3)n3Unlocked=false;page=p;archive=false;buildPage();if(p!=4)load();else if(cache.isEmpty())load();}
 private void pinDialog(){String saved=getSharedPreferences(PREF,MODE_PRIVATE).getString("n3_pin","");EditText pin=new EditText(this);pin.setHint(saved.isEmpty()?"4 haneli PIN belirleyin":"PIN'inizi girin");pin.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);pin.setGravity(Gravity.CENTER);AlertDialog d=new AlertDialog.Builder(this).setTitle(saved.isEmpty()?"NOT 3 - Özel PIN":"NOT 3 - Kilitli").setView(pin).setNegativeButton("VAZGEÇ",null).setPositiveButton(saved.isEmpty()?"PIN OLUŞTUR":"AÇ",null).create();d.setOnShowListener(z->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->{String s=pin.getText().toString().trim();if(s.length()!=4){show("4 haneli PIN girin.");return;}String h=hash(s);if(saved.isEmpty())getSharedPreferences(PREF,MODE_PRIVATE).edit().putString("n3_pin",h).apply();else if(!saved.equals(h)){show("PIN yanlış.");return;}n3Unlocked=true;page=3;archive=false;d.dismiss();buildPage();load();}));d.show();}
 private String hash(String s){try{byte[] b=MessageDigest.getInstance("SHA-256").digest(s.getBytes("UTF-8"));StringBuilder x=new StringBuilder();for(byte q:b)x.append(String.format(Locale.US,"%02x",q));return x.toString();}catch(Exception e){return s;}}
 private boolean connected(){if(!token().isEmpty())return true;pairDialog();return false;}
 private void pairDialog(){if(list==null)return;list.removeAllViews();list.addView(t("Site ajandanızla bağlantı yapın.",15,true));Button b=new Button(this);b.setText("SİTEYE BAĞLAN");b.setOnClickListener(v->showCodeDialog());list.addView(b);}
 private void showCodeDialog(){EditText code=new EditText(this);code.setHint("6 haneli kod");code.setInputType(InputType.TYPE_CLASS_NUMBER);code.setGravity(Gravity.CENTER);AlertDialog d=new AlertDialog.Builder(this).setTitle("AJANDAM'ı Bağla").setView(code).setNegativeButton("VAZGEÇ",null).setPositiveButton("BAĞLA",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String c=code.getText().toString().trim();if(c.length()!=6){show("6 haneli kodu girin.");return;}new Thread(()->{try{String tok=Api.pair(c,"AJANDAM");getSharedPreferences(PREF,MODE_PRIVATE).edit().putString("token",tok).apply();runOnUiThread(()->{d.dismiss();startServiceNow();load();});}catch(Exception e){runOnUiThread(()->show("Bağlantı olmadı: "+e.getMessage()));}}).start();}));d.show();}
 private void load(){if(token().isEmpty()){pairDialog();return;}new Thread(()->{try{List<Api.Entry> a=Api.agenda(token());runOnUiThread(()->{cache=a;if(page==4){buildPage();}else render(a);});}catch(Exception e){runOnUiThread(()->show("Ajanda alınamadı: "+e.getMessage()));}}).start();}
 private int cat(Api.Entry e){return e.note.startsWith(M2)?2:e.note.startsWith(M3)?3:1;} private String clean(String n){return n.startsWith(M2)||n.startsWith(M3)?n.substring(2):n;} private String pack(int c,String n){return c==2?M2+n:c==3?M3+n:n;} private String titleOf(String n){n=clean(n);int p=n.indexOf('\n');return (p<0?n:n.substring(0,p)).trim();} private String detailOf(String n){n=clean(n);int p=n.indexOf('\n');return p<0?"":n.substring(p+1).trim();}
 private int cardColor(Api.Entry e){if(e.remindAt.isEmpty())return Color.WHITE;String now=new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(new Date());return e.remindAt.compareTo(now)<0?Color.rgb(255,220,220):Color.rgb(220,247,224);}
 private void render(List<Api.Entry> all){if(list==null)return;list.removeAllViews();int n=0;for(Api.Entry e:all){if(cat(e)!=page||e.archived()!=archive)continue;n++;list.addView(entryRow(e),rowParams());}if(n==0)list.addView(t(archive?"Arşiv boş.":"Henüz kayıt yok.",14,false));}
 private View entryRow(Api.Entry e){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.TOP);Button menu=new Button(this);menu.setText("⋮");menu.setTextSize(20);menu.setMinWidth(46);menu.setMinimumWidth(46);menu.setPadding(0,0,0,0);menu.setOnClickListener(x->actionMenu(e));row.addView(menu,new LinearLayout.LayoutParams(48,-1));LinearLayout card=v();card.setPadding(10,5,10,5);GradientDrawable bg=new GradientDrawable();bg.setColor(cardColor(e));bg.setCornerRadius(13);bg.setStroke(1,Color.rgb(185,195,205));card.setBackground(bg);TextView title=t(titleOf(e.note),15,true);card.addView(title);String d=detailOf(e.note);if(!d.isEmpty()){TextView desc=t(d,13,false);desc.setTextColor(Color.DKGRAY);card.addView(desc);}String meta="📅 "+prettyDate(e.date)+(e.remindAt.isEmpty()?"  •  Alarm yok":"   ⏰ "+e.remindAt.replace(e.date,"").trim());TextView m=t(meta,11,false);m.setTextColor(Color.rgb(90,90,90));card.addView(m);card.setOnClickListener(x->actionMenu(e));row.addView(card,new LinearLayout.LayoutParams(0,-2,1));return row;}
 private LinearLayout.LayoutParams rowParams(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,2,0,2);return p;}
 private String prettyDate(String d){try{return new SimpleDateFormat("dd.MM.yyyy",Locale.US).format(new SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(d));}catch(Exception e){return d;}}
 private void actionMenu(Api.Entry e){LinearLayout box=v();String[] labels={"✏  Düzenle","⏰  Alarm","📦  "+(e.archived()?"Arşivden çıkar":"Arşiv"),"🗑  Sil"};AlertDialog dlg=new AlertDialog.Builder(this).setTitle(titleOf(e.note)).setView(box).setNegativeButton("KAPAT",null).create();for(int i=0;i<labels.length;i++){final int k=i;Button b=new Button(this);b.setText(labels[i]);b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL);b.setOnClickListener(x->{dlg.dismiss();if(k==0)editForm(e,false,cat(e),"");else if(k==1)editForm(e,true,cat(e),"");else if(k==2)archive(e,!e.archived());else delete(e);});box.addView(b);}dlg.show();}
 private void editForm(Api.Entry e,boolean alarmOnly,int category,String forcedDay){LinearLayout form=v();form.setPadding(24,4,24,0);EditText title=new EditText(this);title.setHint("Başlık");title.setTextSize(15);title.setSingleLine(true);title.setText(e==null?"":titleOf(e.note));form.addView(title);EditText detail=new EditText(this);detail.setHint("Açıklama");detail.setTextSize(13);detail.setMinLines(2);detail.setText(e==null?"":detailOf(e.note));form.addView(detail);Button date=new Button(this),time=new Button(this);date.setTextSize(12);time.setTextSize(12);form.addView(date);form.addView(time);final Calendar c=Calendar.getInstance();String initial=e!=null?e.date:forcedDay;if(initial!=null&&!initial.isEmpty())try{c.setTime(new SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(initial));}catch(Exception ignored){}final boolean[] hasTime={e!=null&&!e.remindAt.isEmpty()};final String[] day={fmt(c,"yyyy-MM-dd")};if(hasTime[0])try{String[] q=e.remindAt.split(" ");String[] hm=q[1].split(":");c.set(Calendar.HOUR_OF_DAY,Integer.parseInt(hm[0]));c.set(Calendar.MINUTE,Integer.parseInt(hm[1]));}catch(Exception ignored){}date.setText("📅 "+fmt(c,"dd.MM.yyyy"));time.setText(hasTime[0]?String.format(Locale.US,"⏰ %02d:%02d",c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE)):"⏰ Alarm yok");date.setOnClickListener(v->new DatePickerDialog(this,(z,y,m,dd)->{c.set(y,m,dd);day[0]=fmt(c,"yyyy-MM-dd");date.setText("📅 "+fmt(c,"dd.MM.yyyy"));},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show());time.setOnClickListener(v->new TimePickerDialog(this,(z,h,min)->{c.set(Calendar.HOUR_OF_DAY,h);c.set(Calendar.MINUTE,min);hasTime[0]=true;time.setText(String.format(Locale.US,"⏰ %02d:%02d",h,min));},c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE),true).show());AlertDialog dlg=new AlertDialog.Builder(this).setTitle(e==null?"Yeni Not":(alarmOnly?"Alarm":"Düzenle")).setView(form).setNegativeButton("VAZGEÇ",null).setNeutralButton(hasTime[0]?"ALARMI KALDIR":null,null).setPositiveButton("KAYDET",null).create();dlg.setOnShowListener(x->{if(hasTime[0])dlg.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{hasTime[0]=false;time.setText("⏰ Alarm yok");});dlg.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String bas=title.getText().toString().trim(),det=detail.getText().toString().trim();if(bas.isEmpty()){show("Başlık boş olamaz.");return;}String note=pack(category,bas+(det.isEmpty()?"":"\n"+det));String rem=hasTime[0]?day[0]+String.format(Locale.US," %02d:%02d",c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE)):"";dlg.dismiss();if(e==null)save(day[0],note,rem);else update(e.id,day[0],note,rem);});});dlg.show();}
 private void renderCalendar(){body.removeViews(2,Math.max(0,body.getChildCount()-2));CalendarView cv=new CalendarView(this);cv.setFirstDayOfWeek(Calendar.MONDAY);body.addView(cv,new LinearLayout.LayoutParams(-1,-2));TextView dayTitle=t("",15,true);body.addView(dayTitle);ScrollView sc=new ScrollView(this);list=v();sc.addView(list);body.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Calendar c=Calendar.getInstance();if(calendarDay.isEmpty())calendarDay=fmt(c,"yyyy-MM-dd");showCalendarDay(dayTitle);cv.setOnDateChangeListener((view,y,m,d)->{calendarDay=String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d);showCalendarDay(dayTitle);});}
 private void showCalendarDay(TextView title){title.setText("📅 "+prettyDate(calendarDay));list.removeAllViews();int n=0;for(Api.Entry e:cache){if(!e.date.equals(calendarDay)||e.archived()!=archive)continue;if(cat(e)==3&&!n3Unlocked)continue;n++;list.addView(entryRow(e),rowParams());}if(n==0)list.addView(t("Bu gün için kayıt yok.",13,false));}
 private void save(String d,String n,String r){new Thread(()->{try{Api.addEntry(token(),d,n,r);runOnUiThread(()->{show("Kaydedildi");load();});}catch(Exception e){runOnUiThread(()->show("Kaydedilemedi: "+e.getMessage()));}}).start();}
 private void update(int id,String d,String n,String r){new Thread(()->{try{Api.updateEntry(token(),id,d,n,r);runOnUiThread(()->{show("Güncellendi");load();});}catch(Exception e){runOnUiThread(()->show("Güncellenemedi: "+e.getMessage()));}}).start();}
 private void archive(Api.Entry e,boolean a){new Thread(()->{try{Api.archive(token(),e.id,a);runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->show(x.getMessage()));}}).start();}
 private void delete(Api.Entry e){new AlertDialog.Builder(this).setTitle("Notu Sil").setMessage("Bu not silinsin mi?").setNegativeButton("HAYIR",null).setPositiveButton("SİL",(d,w)->new Thread(()->{try{Api.deleteEntry(token(),e.id);runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->show(x.getMessage()));}}).start()).show();}
 private void show(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} private String token(){return getSharedPreferences(PREF,MODE_PRIVATE).getString("token","");} private LinearLayout v(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);return x;} private TextView t(String s,int z,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(Color.BLACK);if(b)x.setTypeface(null,Typeface.BOLD);x.setPadding(5,3,5,3);return x;} private String fmt(Calendar c,String p){return new SimpleDateFormat(p,Locale.US).format(c.getTime());}
 private void startServiceNow(){Intent i=new Intent(this,SyncService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);} private void requestPermissionsIfNeeded(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},20);}
}
