package com.musteritakipcrm.alarm;

import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.os.*;import android.text.InputType;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;

public class MainActivity extends Activity{
 private static final String PREF="crm_alarm"; private LinearLayout list; private boolean archive=false;
 private final int[] CARD_COLORS={Color.rgb(255,248,196),Color.rgb(225,245,254),Color.rgb(232,245,233),Color.rgb(255,235,238),Color.rgb(243,229,245),Color.rgb(255,243,224)};
 @Override public void onCreate(Bundle b){super.onCreate(b);AlarmRingingService.ensureChannels(this);requestPermissionsIfNeeded();setContentView(ui());if(token().isEmpty())pairDialog();else{startServiceNow();load();}}
 private LinearLayout ui(){LinearLayout root=v();root.setBackgroundColor(Color.rgb(240,247,252));TextView h=t("📝  AJANDAM",25,true);h.setPadding(26,22,26,22);h.setBackgroundColor(Color.rgb(255,202,40));root.addView(h,new LinearLayout.LayoutParams(-1,-2));LinearLayout body=v();body.setPadding(18,16,18,18);root.addView(body,new LinearLayout.LayoutParams(-1,-1));Button add=new Button(this);add.setText("+  YENİ NOT");add.setTextSize(18);add.setOnClickListener(x->{if(connected())newNote();});body.addView(add);LinearLayout tabs=new LinearLayout(this);Button notes=new Button(this);notes.setText("NOTLAR");Button ar=new Button(this);ar.setText("ARŞİV");notes.setOnClickListener(x->{archive=false;if(connected())load();});ar.setOnClickListener(x->{archive=true;if(connected())load();});tabs.addView(notes,new LinearLayout.LayoutParams(0,-2,1));tabs.addView(ar,new LinearLayout.LayoutParams(0,-2,1));body.addView(tabs);ScrollView sc=new ScrollView(this);list=v();sc.addView(list);body.addView(sc,new LinearLayout.LayoutParams(-1,0,1));return root;}
 private boolean connected(){if(!token().isEmpty())return true;pairDialog();return false;}
 private void pairDialog(){list.removeAllViews();list.addView(t("Site ajandanızla senkronize etmek için bir kez bağlantı yapın.",17,true));Button b=new Button(this);b.setText("SİTEYE BAĞLAN");b.setOnClickListener(v->showCodeDialog());list.addView(b);}
 private void showCodeDialog(){EditText code=new EditText(this);code.setHint("6 haneli bağlantı kodu");code.setInputType(InputType.TYPE_CLASS_NUMBER);code.setTextSize(24);code.setGravity(Gravity.CENTER);code.setPadding(30,30,30,30);AlertDialog d=new AlertDialog.Builder(this).setTitle("AJANDAM'ı Bağla").setMessage("Sitede Telefon Alarmını Bağla düğmesine basın. Çıkan 6 haneli kodu buraya yazın.").setView(code).setNegativeButton("VAZGEÇ",null).setPositiveButton("BAĞLA",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String c=code.getText().toString().trim();if(c.length()!=6){show("6 haneli kodu girin.");return;}d.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(false);new Thread(()->{try{String tok=Api.pair(c,"AJANDAM");getSharedPreferences(PREF,MODE_PRIVATE).edit().putString("token",tok).apply();runOnUiThread(()->{d.dismiss();show("Bağlandı. Ajanda senkronize ediliyor.");startServiceNow();load();});}catch(Exception e){runOnUiThread(()->{d.getButton(AlertDialog.BUTTON_POSITIVE).setEnabled(true);show("Bağlantı olmadı: "+e.getMessage());});}}).start();}));d.show();}
 private void load(){String tok=token();if(tok.isEmpty()){pairDialog();return;}list.removeAllViews();list.addView(t("Senkronize ediliyor...",16,false));new Thread(()->{try{List<Api.Entry> all=Api.agenda(tok);runOnUiThread(()->render(all));}catch(Exception e){runOnUiThread(()->show("Ajanda alınamadı: "+e.getMessage()));}}).start();}
 private void render(List<Api.Entry> all){list.removeAllViews();int n=0;for(Api.Entry e:all){if(e.archived()!=archive)continue;int idx=n++;LinearLayout card=v();card.setPadding(18,14,18,14);GradientDrawable bg=new GradientDrawable();bg.setColor(CARD_COLORS[idx%CARD_COLORS.length]);bg.setCornerRadius(22);bg.setStroke(3,Color.rgb(60,130,190));card.setBackground(bg);TextView note=t(e.note,18,true);card.addView(note);String meta=e.date+(e.remindAt.isEmpty()?"":"     ⏰ "+e.remindAt.replace(e.date,"").trim());TextView m=t(meta,14,false);m.setTextColor(Color.rgb(80,80,80));card.addView(m);TextView hint=t("Dokun → Sil • Düzenle • Arşiv • Alarm",12,false);hint.setTextColor(Color.rgb(80,110,140));card.addView(hint);card.setClickable(true);card.setOnClickListener(x->actionMenu(e));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,7,0,9);list.addView(card,p);}if(n==0)list.addView(t(archive?"Arşiv boş.":"Henüz not yok. + YENİ NOT ile ekleyin.",16,false));}
 private void actionMenu(Api.Entry e){String archiveText=e.archived()?"↩ ARŞİVDEN ÇIKAR":"📦 ARŞİV";String alarmText=e.remindAt.isEmpty()?"⏰ ALARM EKLE":"⏰ ALARMI DEĞİŞTİR";String[] a={"✏ DÜZENLE",alarmText,archiveText,"🗑 SİL"};new AlertDialog.Builder(this).setTitle(e.note).setItems(a,(d,w)->{if(w==0)editNote(e,false);else if(w==1)editNote(e,true);else if(w==2)archive(e,!e.archived());else delete(e);}).setNegativeButton("KAPAT",null).show();}
 private void newNote(){editForm(null,false);}
 private void editNote(Api.Entry e,boolean alarmOnly){editForm(e,alarmOnly);}
 private void editForm(Api.Entry e,boolean alarmOnly){LinearLayout form=v();form.setPadding(36,10,36,0);EditText note=new EditText(this);note.setHint("Notunuzu yazın");note.setMinLines(3);note.setText(e==null?"":e.note);form.addView(note);Button date=new Button(this);Button time=new Button(this);form.addView(date);form.addView(time);final Calendar c=Calendar.getInstance();if(e!=null&&!e.date.isEmpty()){try{c.setTime(new SimpleDateFormat("yyyy-MM-dd",Locale.US).parse(e.date));}catch(Exception ignored){}}final boolean[] hasTime={e!=null&&!e.remindAt.isEmpty()};final String[] day={fmt(c,"yyyy-MM-dd")};if(hasTime[0]){try{String[] q=e.remindAt.split(" ");if(q.length>1){String[] hm=q[1].split(":");c.set(Calendar.HOUR_OF_DAY,Integer.parseInt(hm[0]));c.set(Calendar.MINUTE,Integer.parseInt(hm[1]));}}catch(Exception ignored){}}date.setText("TARİH: "+fmt(c,"dd.MM.yyyy"));time.setText(hasTime[0]?String.format(Locale.getDefault(),"ALARM: %02d:%02d",c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE)):"ALARM SAATİ SEÇ (İSTEĞE BAĞLI)");date.setOnClickListener(v->new DatePickerDialog(this,(d,y,m,dd)->{c.set(y,m,dd);day[0]=fmt(c,"yyyy-MM-dd");date.setText("TARİH: "+fmt(c,"dd.MM.yyyy"));},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show());time.setOnClickListener(v->new TimePickerDialog(this,(d,h,min)->{c.set(Calendar.HOUR_OF_DAY,h);c.set(Calendar.MINUTE,min);hasTime[0]=true;time.setText(String.format(Locale.getDefault(),"ALARM: %02d:%02d",h,min));},c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE),true).show());AlertDialog dlg=new AlertDialog.Builder(this).setTitle(e==null?"Yeni Not":(alarmOnly?"Alarm":"Notu Düzenle")).setView(form).setNegativeButton("VAZGEÇ",null).setPositiveButton("KAYDET",null).create();dlg.setOnShowListener(x->dlg.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String n=note.getText().toString().trim();if(n.isEmpty()){show("Not boş olamaz.");return;}String rem=hasTime[0]?day[0]+String.format(Locale.US," %02d:%02d",c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE)):"";dlg.dismiss();if(e==null)save(day[0],n,rem);else update(e.id,day[0],n,rem);}));dlg.show();}
 private void save(String d,String n,String r){new Thread(()->{try{Api.addEntry(token(),d,n,r);runOnUiThread(()->{show("Not kaydedildi");load();});}catch(Exception e){runOnUiThread(()->show("Kaydedilemedi: "+e.getMessage()));}}).start();}
 private void update(int id,String d,String n,String r){new Thread(()->{try{Api.updateEntry(token(),id,d,n,r);runOnUiThread(()->{show("Not güncellendi");load();});}catch(Exception e){runOnUiThread(()->show("Güncellenemedi: "+e.getMessage()));}}).start();}
 private void archive(Api.Entry e,boolean a){new Thread(()->{try{Api.archive(token(),e.id,a);runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->show(x.getMessage()));}}).start();}
 private void delete(Api.Entry e){new AlertDialog.Builder(this).setTitle("Notu Sil").setMessage("Bu not kalıcı olarak silinsin mi?").setNegativeButton("HAYIR",null).setPositiveButton("SİL",(d,w)->new Thread(()->{try{Api.deleteEntry(token(),e.id);runOnUiThread(this::load);}catch(Exception x){runOnUiThread(()->show(x.getMessage()));}}).start()).show();}
 private void show(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} private String token(){return getSharedPreferences(PREF,MODE_PRIVATE).getString("token","");}
 private LinearLayout v(){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);return x;} private TextView t(String s,int z,boolean b){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(Color.BLACK);if(b)x.setTypeface(null,Typeface.BOLD);x.setPadding(8,10,8,10);return x;} private String fmt(Calendar c,String p){return new SimpleDateFormat(p,Locale.US).format(c.getTime());}
 private void startServiceNow(){Intent i=new Intent(this,SyncService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);} private void requestPermissionsIfNeeded(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},20);}
}
