package com.musteritakipcrm.alarm;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.media.MediaRecorder;import android.os.*;import android.speech.RecognizerIntent;import android.view.Gravity;import android.widget.*;import java.io.File;import java.text.SimpleDateFormat;import java.util.*;
public class MeetingActivity extends Activity{
 private static final int REQ_MIC=41,REQ_SPEECH=42;private EditText title,text;private TextView status;private MediaRecorder recorder;private File audioFile;private boolean recording=false;
 @Override public void onCreate(Bundle b){super.onCreate(b);build();}
 private void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(20,20,20,20);root.setBackgroundColor(Color.rgb(247,244,234));TextView h=new TextView(this);h.setText("🎙 TOPLANTI NOTLARI");h.setTextSize(22);h.setGravity(Gravity.CENTER);h.setPadding(8,18,8,18);h.setBackgroundColor(Color.rgb(255,202,40));root.addView(h,new LinearLayout.LayoutParams(-1,-2));title=new EditText(this);title.setHint("Toplantı / müşteri adı");title.setTextSize(17);root.addView(title);status=new TextView(this);status.setText("Hazır");status.setPadding(8,10,8,8);root.addView(status);LinearLayout buttons=new LinearLayout(this);Button rec=new Button(this);rec.setText("🔴 SES KAYDI");rec.setOnClickListener(v->{if(recording)stopRecording();else startRecording();});Button speech=new Button(this);speech.setText("🗣 YAZIYA ÇEVİR");speech.setOnClickListener(v->speechToText());buttons.addView(rec,new LinearLayout.LayoutParams(0,-2,1));buttons.addView(speech,new LinearLayout.LayoutParams(0,-2,1));root.addView(buttons);text=new EditText(this);text.setHint("Toplantı konuşmaları / notlar...");text.setGravity(Gravity.TOP);text.setMinLines(10);root.addView(text,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bottom=new LinearLayout(this);Button save=new Button(this);save.setText("☁ CRM'YE KAYDET");save.setOnClickListener(v->saveCloud());Button copy=new Button(this);copy.setText("📋 KOPYALA");copy.setOnClickListener(v->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Toplantı",text.getText()));Toast.makeText(this,"Metin panoya kopyalandı.",Toast.LENGTH_SHORT).show();});Button share=new Button(this);share.setText("✉ MAIL");share.setOnClickListener(v->share());bottom.addView(save,new LinearLayout.LayoutParams(0,-2,1));bottom.addView(copy,new LinearLayout.LayoutParams(0,-2,1));bottom.addView(share,new LinearLayout.LayoutParams(0,-2,1));root.addView(bottom);setContentView(root);}
 private String token(){return getSharedPreferences("crm_alarm",MODE_PRIVATE).getString("token","");}
 private void saveCloud(){String tr=text.getText().toString().trim();if(tr.isEmpty()){Toast.makeText(this,"Önce toplantı notunu yazın veya yazıya çevirin.",Toast.LENGTH_LONG).show();return;}status.setText("Bilgisayarla senkronlanıyor...");new Thread(()->{try{Api.addMeeting(token(),title.getText().toString().trim().isEmpty()?"Toplantı":title.getText().toString().trim(),tr,audioFile==null?"":audioFile.getName());runOnUiThread(()->status.setText("✓ Toplantı notu CRM ile senkronlandı"));}catch(Exception e){runOnUiThread(()->status.setText("Senkron hatası: "+e.getMessage()));}}).start();}
 private void startRecording(){if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}try{audioFile=new File(getExternalFilesDir(null),"toplanti_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.US).format(new Date())+".m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setOutputFile(audioFile.getAbsolutePath());recorder.prepare();recorder.start();recording=true;status.setText("🔴 Ses kaydı yapılıyor");}catch(Exception e){status.setText("Kayıt başlatılamadı: "+e.getMessage());}}
 private void stopRecording(){try{recorder.stop();}catch(Exception ignored){}try{recorder.release();}catch(Exception ignored){}recorder=null;recording=false;status.setText("Ses kaydı kaydedildi: "+(audioFile==null?"":audioFile.getName()));}
 private void speechToText(){if(recording){Toast.makeText(this,"Önce ses kaydını durdurun. Bazı telefonlarda iki işlem aynı mikrofonu aynı anda kullanamaz.",Toast.LENGTH_LONG).show();return;}Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"tr-TR");try{startActivityForResult(i,REQ_SPEECH);}catch(Exception e){Toast.makeText(this,"Konuşmayı yazıya çevirme servisi bulunamadı.",Toast.LENGTH_LONG).show();}}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==REQ_SPEECH&&c==RESULT_OK&&d!=null){ArrayList<String>a=d.getStringArrayListExtra(RecognizerIntent.EXTRA_RESULTS);if(a!=null&&!a.isEmpty()){if(text.length()>0)text.append("\n");text.append(a.get(0));}}}
 private void share(){Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_SUBJECT,"AJANDAM - "+(title.getText().length()==0?"Toplantı Notu":title.getText().toString()));i.putExtra(Intent.EXTRA_TEXT,text.getText().toString());startActivity(Intent.createChooser(i,"Mail gönder"));}
 @Override protected void onDestroy(){if(recording)stopRecording();super.onDestroy();}
}
