import worker from './customer_mail_entry.js';
import { connect } from 'cloudflare:sockets';

const HOST='mail.trweb.net', USER='ali@jetlazer.com', SMTP_PORT=587, POP_PORT=110, POP_TLS_PORT=995;
const enc=new TextEncoder();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const clean=v=>String(v||'').replace(/[\r\n]+/g,' ').trim();
function b64bytes(bytes){let s='';for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(s)}
const b64=v=>b64bytes(enc.encode(String(v||'')));
function b64text(v){try{const bin=atob(String(v||'').replace(/\s+/g,'')),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new TextDecoder().decode(a)}catch{return String(v||'')}}
async function limit(p,ms,msg){let t;try{return await Promise.race([p,new Promise((_,r)=>t=setTimeout(()=>r(new Error(msg)),ms))])}finally{clearTimeout(t)}}
async function admin(request,env,ctx){try{const u=new URL(request.url);u.pathname='/api/session';u.search='';const r=await worker.fetch(new Request(u,{headers:request.headers}),env,ctx);return r.ok&&(await r.json()).role==='admin'}catch{return false}}
function io(socket){let reader=socket.readable.getReader(),buf='';const dec=new TextDecoder();return {async line(){for(;;){const i=buf.indexOf('\n');if(i>=0){const x=buf.slice(0,i).replace(/\r$/,'');buf=buf.slice(i+1);return x}const x=await limit(reader.read(),12000,'Mail sunucusundan cevap alınamadı.');if(x.done)throw new Error('Mail sunucusu bağlantıyı kapattı.');buf+=dec.decode(x.value,{stream:true})}},async raw(s){const w=socket.writable.getWriter();try{await limit(w.write(enc.encode(s)),12000,'Mail sunucusuna yazılamadı.')}finally{w.releaseLock()}},async cmd(s){return this.raw(s+'\r\n')},release(){try{reader.releaseLock()}catch{}}}}
async function smtpReply(x){const lines=[];let code='';for(;;){const line=await x.line();lines.push(line);if(!code)code=line.slice(0,3);if(line.slice(0,3)===code&&line[3]!=='-')return {code:Number(code),text:lines.join('\n')}}}
function expect(r,codes){if(!codes.includes(r.code))throw new Error('SMTP hatası: '+r.text)}
async function smtpLogin(password,keep=false){let socket=connect({hostname:HOST,port:SMTP_PORT},{secureTransport:'starttls'}),x;try{await limit(socket.opened,12000,'SMTP sunucusuna bağlanılamadı.');x=io(socket);expect(await smtpReply(x),[220]);await x.cmd('EHLO crm.jetlazer.com');let eh=await smtpReply(x);expect(eh,[250]);if(!/STARTTLS/i.test(eh.text))throw new Error('SMTP sunucusu TLS desteklemiyor.');await x.cmd('STARTTLS');expect(await smtpReply(x),[220]);x.release();socket=socket.startTls();await limit(socket.opened,12000,'SMTP TLS bağlantısı kurulamadı.');x=io(socket);await x.cmd('EHLO crm.jetlazer.com');expect(await smtpReply(x),[250]);await x.cmd('AUTH LOGIN');expect(await smtpReply(x),[334]);await x.cmd(b64(USER));expect(await smtpReply(x),[334]);await x.cmd(b64(password));expect(await smtpReply(x),[235]);if(keep)return {socket,x};try{await x.cmd('QUIT')}catch{}try{await socket.close()}catch{}return true}catch(e){try{x?.release()}catch{}try{await socket?.close()}catch{}throw e}}
function message(to,subject,body){const id='<crm-'+Date.now()+'-'+crypto.randomUUID().slice(0,8)+'@jetlazer.com>',body64=b64(body).match(/.{1,76}/g)?.join('\r\n')||'';return {id,data:['From: Jet Lazer <'+USER+'>','To: <'+clean(to)+'>','Subject: =?UTF-8?B?'+b64(clean(subject))+'?=','Date: '+new Date().toUTCString(),'Message-ID: '+id,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','Content-Transfer-Encoding: base64','',''+body64,''].join('\r\n')}}
async function sendMail(to,subject,body,password){const {socket,x}=await smtpLogin(password,true),m=message(to,subject,body);try{await x.cmd('MAIL FROM:<'+USER+'>');expect(await smtpReply(x),[250]);await x.cmd('RCPT TO:<'+clean(to)+'>');expect(await smtpReply(x),[250,251]);await x.cmd('DATA');expect(await smtpReply(x),[354]);await x.raw(m.data+'\r\n.\r\n');expect(await smtpReply(x),[250]);try{await x.cmd('QUIT')}catch{}return m.id}finally{try{x.release()}catch{}try{await socket.close()}catch{}}}

async function popMulti(x){const a=[];for(;;){const s=await x.line();if(s==='.')return a;a.push(s.startsWith('..')?s.slice(1):s)}}
function popOk(s){if(!String(s||'').startsWith('+OK'))throw new Error('POP3 hatası: '+s)}
async function popOpen(){let socket,x;try{socket=connect({hostname:HOST,port:POP_TLS_PORT},{secureTransport:'on'});await limit(socket.opened,6500,'POP3 TLS başarısız.');x=io(socket);popOk(await x.line());return {socket,x,mode:'TLS/995'}}catch{try{x?.release()}catch{}try{await socket?.close()}catch{}}socket=connect({hostname:HOST,port:POP_PORT},{secureTransport:'starttls'});await limit(socket.opened,10000,'POP3 sunucusuna bağlanılamadı.');x=io(socket);popOk(await x.line());await x.cmd('STLS');const r=await x.line();if(!r.startsWith('+OK')){try{await socket.close()}catch{}throw new Error('POP3 güvenli TLS bağlantısını kabul etmedi. Parola düz bağlantıdan gönderilmedi.')}x.release();socket=socket.startTls();await limit(socket.opened,10000,'POP3 TLS bağlantısı kurulamadı.');return {socket,x:io(socket),mode:'STARTTLS/110'}}
const unfold=s=>String(s||'').replace(/\r?\n[ \t]+/g,' ');
function hv(raw,name){const m=unfold(raw).match(new RegExp('^'+name+':\\s*(.*)$','im'));return m?m[1].trim():''}
function mime(v){return String(v||'').replace(/=\?[^?]+\?([bBqQ])\?([^?]+)\?=/g,(_,k,d)=>k.toLowerCase()==='b'?b64text(d):(()=>{const q=d.replace(/_/g,' ').replace(/=([0-9A-F]{2})/gi,'%$1');try{return decodeURIComponent(q)}catch{return d}})())}
function addr(v){const s=mime(v),m=s.match(/<([^<>\s]+@[^<>\s]+)>/)||s.match(/([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,})/i);return m?m[1].toLowerCase():''}
function qp(v){const s=String(v||'').replace(/=\r?\n/g,''),a=[];for(let i=0;i<s.length;i++){if(s[i]==='='&&/^[0-9A-F]{2}$/i.test(s.slice(i+1,i+3))){a.push(parseInt(s.slice(i+1,i+3),16));i+=2}else a.push(s.charCodeAt(i)&255)}return new TextDecoder().decode(new Uint8Array(a))}
function transfer(body,e){e=String(e||'').toLowerCase();return e.includes('base64')?b64text(body):e.includes('quoted-printable')?qp(body):String(body||'')}
const strip=s=>String(s||'').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/p>/gi,'\n').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/[ \t]+/g,' ').trim();
function parseMail(raw){const a=String(raw||'').split(/\r?\n\r?\n/),h=a.shift()||'',body=a.join('\r\n\r\n'),ct=hv(h,'Content-Type'),te=hv(h,'Content-Transfer-Encoding');let text='',bm=ct.match(/boundary=(?:"([^"]+)"|([^;\s]+))/i);if(/multipart\//i.test(ct)&&bm){let html='';for(const p of body.split('--'+(bm[1]||bm[2]))){const z=p.split(/\r?\n\r?\n/),ph=z.shift()||'',pb=z.join('\r\n\r\n'),pct=hv(ph,'Content-Type'),pe=hv(ph,'Content-Transfer-Encoding');if(/^text\/plain/i.test(pct)&&!text)text=transfer(pb,pe).trim();else if(/^text\/html/i.test(pct)&&!html)html=strip(transfer(pb,pe))}if(!text)text=html}else{text=transfer(body,te);if(/text\/html/i.test(ct))text=strip(text)}const d=new Date(hv(h,'Date'));return {from:addr(hv(h,'From')),subject:mime(hv(h,'Subject')||'Konu yok'),body:String(text||'').trim().slice(0,60000),date:Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString()}}
function emails(c){const out=[],add=v=>{v=String(v||'').trim().toLowerCase();if(v&&v.includes('@')&&!out.includes(v))out.push(v)};add(c?.email);for(const k of ['emails_json','contacts_json'])try{const a=Array.isArray(c?.[k])?c[k]:JSON.parse(c?.[k]||'[]');a.forEach(v=>typeof v==='string'?add(v):add(v?.email))}catch{}return out}
async function customer(env,id){return env.DB.prepare('SELECT * FROM customers WHERE id=?').bind(Number(id)).first()}
function contactIso(value){const d=new Date(value||Date.now());return Number.isNaN(d.getTime())?new Date().toISOString():d.toISOString()}
async function touchLastContact(env,c,when){
  const at=contactIso(when),now=new Date().toISOString();
  try{
    await env.DB.prepare(`INSERT INTO sales_care(customer_id,customer_name,last_contact_at,created_at,updated_at)
      VALUES(?,?,?,?,?) ON CONFLICT(customer_id) DO UPDATE SET customer_name=excluded.customer_name,
      last_contact_at=CASE WHEN sales_care.last_contact_at='' OR sales_care.last_contact_at<excluded.last_contact_at THEN excluded.last_contact_at ELSE sales_care.last_contact_at END,
      updated_at=excluded.updated_at`).bind(Number(c.id),clean(c.company),at,now,now).run();
    const row=await env.DB.prepare('SELECT last_contact_at FROM sales_care WHERE customer_id=?').bind(Number(c.id)).first();
    return clean(row?.last_contact_at)||at;
  }catch(e){console.error('last-contact',e);return at}
}
async function syncMail(env,c,password){const allowed=emails(c);if(!allowed.length)throw new Error('Bu müşterinin kayıtlı mail adresi yok.');const {socket,x,mode}=await popOpen();let added=0,checked=0;try{await x.cmd('USER '+USER);popOk(await x.line());await x.cmd('PASS '+password);popOk(await x.line());await x.cmd('UIDL');popOk(await x.line());const rows=(await popMulti(x)).map(v=>{const p=v.trim().split(/\s+/);return {n:Number(p[0]),uid:p.slice(1).join(' ')}}).filter(v=>v.n&&v.uid).slice(-35).reverse();for(const item of rows){const ext='pop3:'+item.uid;if(await env.DB.prepare('SELECT id FROM mails WHERE external_id=? LIMIT 1').bind(ext).first())continue;checked++;await x.cmd('RETR '+item.n);popOk(await x.line());const m=parseMail((await popMulti(x)).join('\r\n'));if(!m.from||!allowed.includes(m.from))continue;await env.DB.prepare('INSERT INTO mails(customer_id,direction,mail_date,email,subject,summary,follow_date,external_id,created_at) VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(Number(c.id),'Gelen',m.date,m.from,m.subject,m.body,'',ext).run();added++}try{await x.cmd('QUIT')}catch{}const last=await env.DB.prepare('SELECT MAX(mail_date) AS last_at FROM mails WHERE customer_id=?').bind(Number(c.id)).first();const lastContact=last?.last_at?await touchLastContact(env,c,last.last_at):'';return {added,checked,mode,last_contact_at:lastContact}}finally{try{x.release()}catch{}try{await socket.close()}catch{}}}

const PATCH=String.raw`(function(){
 if(window.__crmDirectMailTransport)return;window.__crmDirectMailTransport='v1';
 var KEY='crm_mail_session_password';
 var css=document.createElement('style');css.textContent='#portfolioDetailExpandModal .crm-mail-transport{border:1px solid #fecaca;border-radius:10px;background:#fff7f7;padding:10px;margin-bottom:10px}#portfolioDetailExpandModal .crm-mail-transport summary{cursor:pointer;font-weight:950;color:#991b1b}#portfolioDetailExpandModal .crm-mail-row{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:8px}#portfolioDetailExpandModal .crm-mail-row label{font-size:10px;font-weight:900;color:#64748b}#portfolioDetailExpandModal .crm-mail-row input{width:100%;margin-top:3px}#portfolioDetailExpandModal .crm-mail-tools{display:flex;gap:7px;align-items:center;justify-content:flex-end;flex-wrap:wrap;margin-top:8px}#portfolioDetailExpandModal .crm-mail-tools button{border:0;border-radius:8px;padding:8px 10px;font-weight:900;cursor:pointer}#portfolioDetailExpandModal .crm-mail-test{background:#e0e7ff;color:#3730a3}#portfolioDetailExpandModal .crm-mail-sync{background:#dbeafe;color:#1d4ed8}#portfolioDetailExpandModal .crm-mail-msg{margin-right:auto;font-size:10px;font-weight:900;color:#15803d}.crm-mail-msg.err{color:#dc2626}@media(max-width:700px){#portfolioDetailExpandModal .crm-mail-row{grid-template-columns:1fr}}';document.head.appendChild(css);
 async function api(path,data){var r=await fetch(path,{method:'POST',headers:{'content-type':'application/json','cache-control':'no-cache'},body:JSON.stringify(data)}),d={};try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d.error||'Mail işlemi başarısız.');return d}
 function pass(panel,msg){var i=panel.querySelector('[data-transport-pass]'),v=String(i&&i.value||sessionStorage.getItem(KEY)||'');if(v){sessionStorage.setItem(KEY,v);return v}msg.textContent='Önce mail parolasını gir.';msg.className='crm-mail-msg err';panel.querySelector('.crm-mail-transport').open=true;i?.focus();return ''}
 function customerId(panel){return Number(panel.getAttribute('data-customer-id')||0)}
 function decorate(panel){if(!panel||panel.dataset.transportReady==='1')return;panel.dataset.transportReady='1';var compose=panel.querySelector('.pie-mail-compose');if(!compose)return;var box=document.createElement('details');box.className='crm-mail-transport';box.innerHTML='<summary>⚙️ ali@jetlazer.com Bağlantısı</summary><div class="crm-mail-row"><label>Sunucu<input value="mail.trweb.net" readonly></label><label>SMTP<input value="587 / TLS" readonly></label><label>Hesap<input value="ali@jetlazer.com" readonly></label><label>Mail Parolası<input type="password" data-transport-pass autocomplete="current-password" placeholder="Parola bu oturumda tutulur"></label></div><div class="crm-mail-tools"><span class="crm-mail-msg" data-transport-msg></span><button type="button" class="crm-mail-test">Bağlantıyı Test Et</button><button type="button" class="crm-mail-sync">📥 Gelenleri Getir</button></div><div class="pie-mail-note">Parola GitHub veya CRM veritabanına kaydedilmez; yalnızca bu tarayıcı oturumunda tutulur.</div>';compose.insertAdjacentElement('beforebegin',box);var input=box.querySelector('[data-transport-pass]');input.value=sessionStorage.getItem(KEY)||'';input.oninput=function(){sessionStorage.setItem(KEY,this.value)};var msg=box.querySelector('[data-transport-msg]');box.querySelector('.crm-mail-test').onclick=async function(){var p=pass(panel,msg);if(!p)return;this.disabled=true;msg.textContent='Bağlantı deneniyor...';msg.className='crm-mail-msg';try{await api('/api/customer-mail/test',{password:p});msg.textContent='✅ Gönderim bağlantısı hazır.'}catch(e){msg.textContent=e.message;msg.className='crm-mail-msg err'}finally{this.disabled=false}};box.querySelector('.crm-mail-sync').onclick=async function(){var p=pass(panel,msg),id=customerId(panel);if(!p||!id)return;this.disabled=true;msg.textContent='Gelen kutusu kontrol ediliyor...';msg.className='crm-mail-msg';try{var d=await api('/api/customer-mail/sync',{password:p,customer_id:id});msg.textContent='✅ '+d.added+' yeni mail alındı. ('+d.mode+')';if(d.last_contact_at)window.dispatchEvent(new CustomEvent('crm-last-contact-updated',{detail:{customer_id:id,last_contact_at:d.last_contact_at}}));panel.querySelector('[data-mail-refresh]')?.click()}catch(e){msg.textContent=e.message;msg.className='crm-mail-msg err'}finally{this.disabled=false}};
 var old=panel.querySelector('[data-mail-send]');if(old){var btn=old.cloneNode(true);old.replaceWith(btn);btn.textContent='✉️ Şimdi Gönder';btn.onclick=async function(){var s=panel.querySelector('[data-mail-status]'),p=pass(panel,s);if(!p)return;var to=String(panel.querySelector('[data-mail-to]')?.value||'').trim(),subject=String(panel.querySelector('[data-mail-subject]')?.value||'').trim(),body=String(panel.querySelector('[data-mail-body]')?.value||'').trim(),id=customerId(panel);if(!to||!subject||!body){s.textContent=!to?'Müşterinin mail adresi yok.':!subject?'Konu boş olamaz.':'Mesaj boş olamaz.';s.className='pie-mail-status err';return}btn.disabled=true;s.textContent='Mail gönderiliyor...';s.className='pie-mail-status';try{var d=await api('/api/customer-mail/send',{password:p,customer_id:id,to:to,subject:subject,body:body});if(d.last_contact_at)window.dispatchEvent(new CustomEvent('crm-last-contact-updated',{detail:{customer_id:id,last_contact_at:d.last_contact_at}}));s.textContent='✅ Mail gönderildi ve CRM’ye kaydedildi.';panel.querySelector('[data-mail-subject]').value='';panel.querySelector('[data-mail-body]').value='';panel.querySelector('[data-mail-refresh]')?.click()}catch(e){s.textContent=e.message;s.className='pie-mail-status err'}finally{btn.disabled=false}};var note=compose.querySelector('.pie-mail-note');if(note)note.textContent='Mail doğrudan ali@jetlazer.com hesabından gönderilir; başarılı gönderim CRM geçmişine otomatik kaydolur.'}
 }
 function scan(){document.querySelectorAll('#portfolioDetailExpandModal .pie-mail-panel').forEach(decorate)}
 new MutationObserver(function(){setTimeout(scan,0)}).observe(document.documentElement,{subtree:true,childList:true});setInterval(scan,700);scan();
})();`;

function rebuild(response,html){const h=new Headers(response.headers);for(const n of ['content-length','content-encoding','etag'])h.delete(n);h.set('cache-control','no-cache, no-store, must-revalidate');return new Response(html,{status:response.status,statusText:response.statusText,headers:h})}

export default{
 async fetch(request,env,ctx){
  const u=new URL(request.url);
  if(request.method==='POST'&&u.pathname.startsWith('/api/customer-mail/')){
   if(!await admin(request,env,ctx))return json({error:'Yetkisiz'},401);let b={};try{b=await request.json()}catch{return json({error:'Geçersiz istek.'},400)}const password=String(b.password||'');if(!password)return json({error:'Mail parolası gerekli.'},400);
   try{
    if(u.pathname==='/api/customer-mail/test'){await smtpLogin(password);return json({ok:true})}
    const c=await customer(env,b.customer_id);if(!c)return json({error:'Müşteri bulunamadı.'},404);
    if(u.pathname==='/api/customer-mail/send'){const to=clean(b.to),subject=clean(b.subject),body=String(b.body||'');if(!to||!subject||!body)return json({error:'Alıcı, konu ve mesaj gerekli.'},400);if(!emails(c).includes(to.toLowerCase()))return json({error:'Alıcı adresi bu müşteri kartına kayıtlı değil.'},400);const id=await sendMail(to,subject,body,password),sentAt=new Date().toISOString();await env.DB.prepare('INSERT INTO mails(customer_id,direction,mail_date,email,subject,summary,follow_date,external_id,created_at) VALUES(?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind(Number(c.id),'Giden',sentAt,to,subject,body,'',id).run();const lastContact=await touchLastContact(env,c,sentAt);return json({ok:true,last_contact_at:lastContact})}
    if(u.pathname==='/api/customer-mail/sync')return json({ok:true,...await syncMail(env,c,password)});
    return json({error:'Mail işlemi bulunamadı.'},404);
   }catch(e){return json({error:String(e?.message||e||'Mail işlemi başarısız.')},502)}
  }
  const r=await worker.fetch(request,env,ctx);if(request.method==='GET'&&u.pathname==='/musteri-portfoyu.html'&&r.ok&&(r.headers.get('content-type')||'').includes('text/html')){let html=await r.text();html=html.replace(/<script[^>]*data-mail-transport[^>]*>[\s\S]*?<\/script>\s*/gi,'');html=html.replace(/<\/body>/i,`<script data-mail-transport="v1">${PATCH}</script>\n</body>`);return rebuild(r,html)}return r;
 },
 async scheduled(controller,env,ctx){if(typeof worker.scheduled==='function')return worker.scheduled(controller,env,ctx)}
};