import worker from './agenda_title_detail_live_safe.js';

const QUICK_REQUEST = String.raw`
<style id="quickRequestWhatsAppSafeStyle">
#quickRequestFloat{position:fixed;right:22px;bottom:22px;z-index:245;border:0;border-radius:999px;background:#dc2626;color:#fff;padding:13px 18px;font-weight:950;font-size:15px;box-shadow:0 8px 24px #0004;cursor:pointer;display:none}
#quickRequestFloat .qr-count{display:inline-grid;place-items:center;min-width:23px;height:23px;margin-left:7px;padding:0 6px;border-radius:999px;background:#fff;color:#b91c1c;font-size:12px}
#quickRequestMenu{color:#fecaca!important;font-weight:900!important}#quickRequestMenu.active,#quickRequestMenu:hover{background:#b91c1c!important;color:#fff!important}
#quickRequestOverlay{position:fixed;inset:0;z-index:360;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(15,23,42,.62)}#quickRequestOverlay.open{display:flex}
#quickRequestBox{width:min(620px,96vw);max-height:90vh;overflow:auto;background:#fff;border-radius:16px;padding:20px;box-shadow:0 25px 80px #0007;border-top:7px solid #dc2626}
#quickRequestBox h2{margin:0 0 5px;color:#991b1b}.qr-help{font-size:13px;color:#64748b;margin-bottom:14px}#quickRequestBox label{display:block;font-size:12px;font-weight:900;color:#475569;margin:10px 0 5px}
#quickRequestBox input,#quickRequestBox textarea{width:100%;border:2px solid #cbd5e1;border-radius:10px;padding:11px;font:inherit;background:#fff}#quickRequestBox textarea{min-height:150px;resize:vertical;line-height:1.45}
.qr-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px}.qr-actions button{border:0;border-radius:9px;padding:10px 13px;font-weight:900;cursor:pointer}.qr-paste{background:#dcfce7;color:#166534}.qr-save{background:#dc2626;color:#fff;margin-left:auto}.qr-close{background:#e2e8f0;color:#334155}
#quickRequests{display:none}.section#quickRequests.active{display:block}.qr-page-head{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;margin:10px 0 14px}.qr-page-head h2{margin:0}.qr-new{border:0;border-radius:9px;padding:10px 13px;background:#dc2626;color:#fff;font-weight:900;cursor:pointer}
#quickRequestList{display:grid;gap:10px}.qr-card{background:#fff;border:1px solid #fecaca;border-left:6px solid #dc2626;border-radius:12px;padding:12px 14px;box-shadow:0 2px 8px #0000000d}.qr-card-top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.qr-title{font-size:16px;font-weight:950;color:#991b1b}.qr-detail{white-space:pre-wrap;line-height:1.45;margin-top:6px;color:#1f2937}.qr-meta{font-size:11px;color:#64748b;margin-top:7px}.qr-done{border:0;border-radius:8px;background:#dcfce7;color:#166534;padding:8px 10px;font-weight:900;cursor:pointer;white-space:nowrap}.qr-empty{padding:24px;text-align:center;background:#fff;border:1px dashed #cbd5e1;border-radius:12px;color:#64748b}
#quickRequestToast{position:fixed;left:50%;bottom:88px;transform:translateX(-50%);z-index:390;display:none;max-width:88vw;background:#111827;color:#fff;border-radius:10px;padding:10px 14px;font-weight:850;text-align:center;box-shadow:0 8px 24px #0004}
body.qr-mobile #quickRequestFloat{left:18px;right:auto;bottom:24px;width:60px;height:60px;padding:0;border-radius:50%;font-size:24px}body.qr-mobile #quickRequestFloat .qr-text{font-size:0}body.qr-mobile #quickRequestFloat .qr-text:after{content:'⚡';font-size:25px}body.qr-mobile #quickRequestFloat .qr-count{position:absolute;right:-4px;top:-5px;margin:0;border:2px solid #fff}
@media(max-width:720px){#quickRequestBox{padding:16px}.qr-save{margin-left:0;flex:1}.qr-actions button{min-height:44px}}
</style>
<script id="quickRequestWhatsAppSafeScript">
(function(){
'use strict';if(window.__quickRequestWhatsAppSafe)return;window.__quickRequestWhatsAppSafe=true;
var state={authorized:false,items:[],loading:false},lastRenderSignature='',isDesktop=!!document.querySelector('.side .menu')&&!!document.querySelector('main.main'),isMobile=!!document.querySelector('.topbar')&&!!document.getElementById('list');if(!isDesktop&&!isMobile)return;if(isMobile)document.body.classList.add('qr-mobile');
function pad(n){return String(n).padStart(2,'0')}function today(){var d=new Date();return d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())}function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}function split(note){var raw=String(note||'').replace(/\r\n/g,'\n').trim(),lines=raw.split('\n');return {title:(lines.shift()||'').trim(),detail:lines.join('\n').trim()}}function isQuick(x){return /^⚡\s+/.test(String(x&&x.note||''))}
async function json(path,opts){var r=await fetch(path,Object.assign({headers:{'content-type':'application/json','cache-control':'no-cache'}},opts||{})),d={};try{d=await r.json()}catch(_){}if(!r.ok)throw new Error(d.error||'İşlem başarısız');return d}
function toast(text){var el=document.getElementById('quickRequestToast');if(!el)return;el.textContent=text;el.style.display='block';clearTimeout(window.__qrToast);window.__qrToast=setTimeout(function(){el.style.display='none'},2600)}
function ensureBase(){
 if(!document.getElementById('quickRequestToast')){var t=document.createElement('div');t.id='quickRequestToast';document.body.appendChild(t)}
 if(!document.getElementById('quickRequestFloat')){var b=document.createElement('button');b.id='quickRequestFloat';b.type='button';b.innerHTML='<span class="qr-text">⚡ NOT DEFTERI</span><span class="qr-count">0</span>';b.onclick=openQuick;document.body.appendChild(b)}
 if(!document.getElementById('quickRequestOverlay')){var o=document.createElement('div');o.id='quickRequestOverlay';o.innerHTML='<div id="quickRequestBox" role="dialog" aria-modal="true"><h2>⚡ NOT DEFTERI</h2><div class="qr-help">WhatsApp mesajını kopyalayın, sonra “WhatsApp’tan Yapıştır”a basın.</div><label>MÜŞTERİ / FİRMA</label><input id="quickRequestCustomer" autocomplete="off" placeholder=""><label>NOT</label><textarea id="quickRequestText" placeholder=""></textarea><div class="qr-actions"><button type="button" class="qr-paste" id="quickRequestPaste">📋 WhatsApp’tan Yapıştır</button><button type="button" class="qr-close" id="quickRequestClose">Kapat</button><button type="button" class="qr-save" id="quickRequestSave">⚡ Kaydet</button></div></div>';o.onclick=function(e){if(e.target===o)closeQuick()};document.body.appendChild(o);document.getElementById('quickRequestPaste').onclick=pasteWhatsApp;document.getElementById('quickRequestClose').onclick=closeQuick;document.getElementById('quickRequestSave').onclick=saveQuick;document.getElementById('quickRequestCustomer').onkeydown=function(e){if(e.key==='Enter'){e.preventDefault();document.getElementById('quickRequestText').focus()}}}
 if(isDesktop)ensureDesktopPage();
}
function ensureDesktopPage(){var menu=document.querySelector('.side .menu'),main=document.querySelector('main.main');if(!menu||!main)return;if(!document.getElementById('quickRequestMenu')){var btn=document.createElement('button');btn.id='quickRequestMenu';btn.type='button';btn.innerHTML='⚡ NOT DEFTERI <span class="qr-menu-count">(0)</span>';var agenda=menu.querySelector('button[data-page="agenda"]');if(agenda)agenda.insertAdjacentElement('beforebegin',btn);else menu.appendChild(btn);btn.onclick=showQuickPage}if(!document.getElementById('quickRequests')){var sec=document.createElement('section');sec.id='quickRequests';sec.className='section';sec.innerHTML='<div class="qr-page-head"><div><h2>⚡ NOT DEFTERI</h2><div class="small">Tamamlanmayan notlar burada kalır ve aynı zamanda Ajanda’ya kaydolur.</div></div><button type="button" class="qr-new">+ Yeni Not</button></div><div id="quickRequestList"></div>';main.appendChild(sec);sec.querySelector('.qr-new').onclick=openQuick}}
function showQuickPage(){document.querySelectorAll('.menu button').forEach(function(x){x.classList.remove('active')});document.getElementById('quickRequestMenu')?.classList.add('active');document.querySelectorAll('.section').forEach(function(x){x.classList.remove('active')});document.getElementById('quickRequests')?.classList.add('active');var title=document.getElementById('title');if(title)title.textContent='NOT DEFTERI';loadQuick()}
function openQuick(){if(!state.authorized)return toast('Önce CRM girişini yapın.');ensureBase();document.getElementById('quickRequestCustomer').value='';document.getElementById('quickRequestText').value='';document.getElementById('quickRequestOverlay').classList.add('open');setTimeout(function(){document.getElementById('quickRequestCustomer')?.focus()},60)}function closeQuick(){document.getElementById('quickRequestOverlay')?.classList.remove('open')}
async function pasteWhatsApp(){var box=document.getElementById('quickRequestText');if(!box)return;try{if(!navigator.clipboard||!navigator.clipboard.readText)throw new Error();var text=await navigator.clipboard.readText();if(!text)return toast('Panoda metin yok. WhatsApp mesajını önce kopyalayın.');box.value=(box.value?box.value+'\n':'')+text;box.focus();toast('WhatsApp mesajı yapıştırıldı.')}catch(_){box.focus();toast('Tarayıcı panoya izin vermedi. Not alanına Ctrl+V ile yapıştırın.')}}
async function saveQuick(){var customer=String(document.getElementById('quickRequestCustomer')?.value||'').trim(),text=String(document.getElementById('quickRequestText')?.value||'').trim();if(!customer)return toast('Müşteri / firma adını yazın.');if(!text)return toast('Notu yazın veya WhatsApp’tan yapıştırın.');try{await json('/api/agenda',{method:'POST',body:JSON.stringify({entry_date:today(),note:'⚡ '+customer+'\n'+text,remind_at:''})});closeQuick();toast('Not Ajanda’ya kaydedildi.');await loadQuick();if(typeof window.loadAgenda==='function')try{await window.loadAgenda()}catch(_){}}catch(e){toast(e.message)}}
async function completeQuick(id){try{await json('/api/agenda/'+id+'/task-done',{method:'POST',body:JSON.stringify({completed_date:today()})});toast('Not tamamlandı.');await loadQuick();if(typeof window.loadAgenda==='function')try{await window.loadAgenda()}catch(_){}}catch(e){toast(e.message)}}
function render(){var count=state.items.length,fc=document.querySelector('#quickRequestFloat .qr-count');if(fc)fc.textContent=String(count);var mc=document.querySelector('#quickRequestMenu .qr-menu-count');if(mc)mc.textContent='('+count+')';var list=document.getElementById('quickRequestList');if(!list)return;var signature=JSON.stringify(state.items.map(function(x){return [Number(x.id),String(x.note||''),String(x.entry_date||'')]}));if(signature===lastRenderSignature)return;lastRenderSignature=signature;if(!count){list.innerHTML='<div class="qr-empty">Bekleyen not yok.</div>';return}list.innerHTML=state.items.map(function(x){var p=split(x.note),title=p.title.replace(/^⚡\s+/,''),date=String(x.entry_date||'');return '<div class="qr-card"><div class="qr-card-top"><div><div class="qr-title">⚡ '+esc(title)+'</div><div class="qr-detail">'+esc(p.detail)+'</div><div class="qr-meta">📅 '+esc(date)+'</div></div><button type="button" class="qr-done" data-qr-done="'+Number(x.id)+'">✓ Tamamlandı</button></div></div>'}).join('');list.querySelectorAll('[data-qr-done]').forEach(function(b){b.onclick=function(){completeQuick(Number(b.getAttribute('data-qr-done')))}})}
async function loadQuick(){if(!state.authorized||state.loading)return;state.loading=true;try{try{await json('/api/agenda/rollover',{method:'POST',body:JSON.stringify({today:today()})})}catch(_){}var items=await json('/api/agenda/active?from='+encodeURIComponent(today()));state.items=Array.isArray(items)?items.filter(function(x){return x.entry_status!=='Yapıldı'&&isQuick(x)}):[];render()}catch(_){state.items=[];render()}finally{state.loading=false}}
async function authorize(){var wasAuthorized=state.authorized;try{var s=await json('/api/session');state.authorized=!!(s&&s.role==='admin')}catch(_){state.authorized=false}ensureBase();var f=document.getElementById('quickRequestFloat');if(f)f.style.display=state.authorized?'block':'none';var m=document.getElementById('quickRequestMenu');if(m)m.style.display=state.authorized?'block':'none';if(state.authorized&&!wasAuthorized)loadQuick()}
ensureBase();authorize();setInterval(authorize,10000);setInterval(function(){if(state.authorized)loadQuick()},45000);document.addEventListener('keydown',function(e){if(e.key==='Escape')closeQuick()});
})();
</script>`;

function rebuild(response,html){const headers=new Headers(response.headers);headers.delete('content-length');headers.delete('content-encoding');headers.delete('etag');headers.set('cache-control','no-cache, no-store, must-revalidate');headers.set('pragma','no-cache');headers.set('expires','0');return new Response(html,{status:response.status,statusText:response.statusText,headers})}

export default{async fetch(request,env,ctx){const response=await worker.fetch(request,env,ctx),backup=response.clone();try{const type=response.headers.get('content-type')||'';if(request.method!=='GET'||!type.includes('text/html'))return response;const html=await response.text();if(html.includes('quickRequestWhatsAppSafeScript'))return rebuild(response,html);const desktop=html.includes('CRM Müşteri Takip')&&html.includes('class="menu"'),mobile=html.includes('id="list"')&&html.includes('Notlarım');if(!desktop&&!mobile)return rebuild(response,html);const next=html.includes('</body>')?html.replace('</body>',QUICK_REQUEST+'\n</body>'):html+QUICK_REQUEST;return rebuild(response,next)}catch(error){console.error('Quick request patch failed',error);return backup}}};
